version: '3.3'

volumes:
  postgres_data:
  media_volumes:
  static_volumes:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:  
    build: .  
    image: tizjourney/foodgram:v1.0
    
    restart: always
    expose:
      - 8000
    volumes:
      - static_volumes:/code/static
      - media_volumes:/code/media
    depends_on:
      - db
    env_file:
      - ./.env 

  nginx:  
    image: nginx:1.19.6-alpine
    restart: always

    volumes:
      - static_volumes:/code/static
      - media_volumes:/code/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - web
