version: '3.3'

volumes:
  postgres_data:
  media_volumes:
  static_volumes:
  ./data/certbot/conf:
  ./data/certbot/www:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:  
    build: .  
    image: tizjourney/foodgram:v1.0
    
    restart: always
    expose:
      - 8000
    volumes:
      - static_volumes:/code/static
      - media_volumes:/code/media
    depends_on:
      - db
    env_file:
      - ./.env 

  nginx:  
    image: nginx:alpine
    restart: always

    volumes:
      - static_volumes:/code/static
      - media_volumes:/code/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443      
    depends_on:
      - web
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
  certbot:
    container_name: service_certbot
    image: certbot/certbot
    volumes:
    - ./data/certbot/conf:/etc/letsencrypt
    - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
