# Generated by Django 3.0.5 on 2021-06-22 19:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=40, null=True, unique=True)),
                ('measurement', models.CharField(help_text='Единица измерения ингридента. Обязательно к заполнению.', max_length=200, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Ингридиент',
                'verbose_name_plural': 'Ингридиенты',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Название рецепта. Обязательно к заполнению.', verbose_name='Название рецепта')),
                ('tags', models.CharField(choices=[('завтрак', 'Breakfeast'), ('обед', 'Dinner'), ('ужин', 'Supper')], default='завтрак', max_length=7)),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Дата создания. По-умолчанию выставляется текущее время.', verbose_name='Дата создания')),
                ('description', models.TextField(blank=True, help_text='Описание рецепта. Необязательно для заполнения', max_length=2000, null=True, verbose_name='Описание')),
                ('cook_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Время приготовления')),
                ('image', models.ImageField(help_text='Загрузка изображения. Опционально.', upload_to='recipes_images/', verbose_name='Изображение')),
                ('author', models.ForeignKey(help_text='Автор рецепта. Заполняется автоматически.', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('ingredients', models.ManyToManyField(blank=True, to='web.Ingredient')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(help_text='Пользователь, на которого подписываются.', on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('user', models.ForeignKey(help_text='Пользователь, который подписывается.', on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик')),
            ],
            options={
                'unique_together': {('user', 'author')},
            },
        ),
    ]
