# Generated by Django 3.0.5 on 2021-06-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20210622_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузка изображения. Опционально.', null=True, upload_to='recipes_images/', verbose_name='Загрузить фото'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.CharField(blank=True, choices=[('breakfest', 'завтрак'), ('lunch', 'обед'), ('dinner', 'ужин')], default='breakfest', max_length=9, null=True),
        ),
    ]
