# Generated by Django 3.0.5 on 2021-06-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20210623_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.CharField(choices=[('breakfest', 'завтрак'), ('lunch', 'обед'), ('dinner', 'ужин')], default='breakfest', max_length=9),
        ),
    ]
