# Generated by Django 3.0.5 on 2021-06-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20210623_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.AddField(
            model_name='recipe',
            name='breakfest_tag',
            field=models.BooleanField(db_index=True, default=0, verbose_name='Завтрак'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='dinner_tag',
            field=models.BooleanField(db_index=True, default=0, verbose_name='Ужин'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='lunch_tag',
            field=models.BooleanField(db_index=True, default=0, verbose_name='Обед'),
            preserve_default=False,
        ),
    ]
