# Generated by Django 3.0.5 on 2021-06-22 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20210623_0114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='breakfest_tag',
            new_name='breakfast_tag',
        ),
    ]
