# Generated by Django 3.0.5 on 2021-06-24 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0008_auto_20210624_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузка изображения. Опционально.', null=True, upload_to='recipes/', verbose_name='Загрузить фото'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(help_text='Рецепт, который понравился пользователю.', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='web.Recipe', verbose_name='Любимый рецепт')),
                ('user', models.ForeignKey(help_text='Пользователь, которому понравился рецепт.', on_delete=django.db.models.deletion.CASCADE, related_name='favoriter', to=settings.AUTH_USER_MODEL, verbose_name='Любитель')),
            ],
            options={
                'unique_together': {('user', 'recipe')},
            },
        ),
    ]
