# Generated by Django 3.0.5 on 2021-06-24 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0009_auto_20210624_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='recipe',
            field=models.ForeignKey(help_text='Пользователи, подписанные на рецепт', on_delete=django.db.models.deletion.CASCADE, related_name='favorite_by_users', to='web.Recipe', verbose_name='Пользователи рецепта'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(help_text='Любимые рецепты пользователя', on_delete=django.db.models.deletion.CASCADE, related_name='favorite_recipes', to=settings.AUTH_USER_MODEL, verbose_name='Любимые рецепты'),
        ),
    ]
