# Generated by Django 3.0.5 on 2021-06-24 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0012_auto_20210625_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='author',
            field=models.ForeignKey(help_text='Пользователь, на которого подписываются.', on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='subscriber',
            field=models.ForeignKey(help_text='Пользователь, который подписывается.', on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_to_user', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик'),
        ),
    ]
