# Generated by Django 3.0.5 on 2021-06-25 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20210625_0250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='measurement',
            new_name='dimension',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='slug',
        ),
    ]
