# Generated by Django 3.0.5 on 2021-06-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20210625_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientQuanity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('dimension', models.CharField(help_text='Единица измерения ингридента. Обязательно к заполнению.', max_length=200, verbose_name='Единица измерения')),
                ('quanity', models.IntegerField(verbose_name='Количество единиц в рецепте')),
            ],
            options={
                'verbose_name': 'Количество ингридиента',
                'verbose_name_plural': 'Количества ингридиентов',
            },
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='web.IngredientQuanity'),
        ),
    ]
