# Generated by Django 3.0.5 on 2021-07-04 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20210625_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='dimension',
            new_name='units',
        ),
        migrations.RenameField(
            model_name='ingredientquanity',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ingredientquanity',
            old_name='dimension',
            new_name='units',
        ),
        migrations.RenameField(
            model_name='ingredientquanity',
            old_name='quanity',
            new_name='value',
        ),
    ]
