# Generated by Django 3.0.5 on 2021-07-04 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20210704_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientquanity',
            name='ingridients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='web.Ingredient', verbose_name='рецепт'),
        ),
        migrations.AlterField(
            model_name='ingredientquanity',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='web.Recipe', verbose_name='ингриденты'),
        ),
    ]
