# Generated by Django 3.0.5 on 2021-07-04 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20210704_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientquanity',
            old_name='ingridients',
            new_name='ingredients',
        ),
        migrations.AlterField(
            model_name='ingredientquanity',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='web.Recipe', verbose_name='ингридент'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredientquanity',
            unique_together={('recipe', 'ingredients')},
        ),
    ]
