# Generated by Django 3.0.5 on 2021-07-04 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20210704_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientquanity',
            old_name='ingredients',
            new_name='ingredient',
        ),
        migrations.AlterUniqueTogether(
            name='ingredientquanity',
            unique_together={('recipe', 'ingredient')},
        ),
    ]
