# Generated by Django 3.0.5 on 2021-07-05 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0020_auto_20210704_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(help_text='Пользователи, у которых рецепт в покупках', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_by_users', to='web.Recipe', verbose_name='В покупках у пользвателя')),
                ('user', models.ForeignKey(help_text='Список покупок пользователя', on_delete=django.db.models.deletion.CASCADE, related_name='recipe_purchases', to=settings.AUTH_USER_MODEL, verbose_name='Список покупок')),
            ],
            options={
                'unique_together': {('user', 'recipe')},
            },
        ),
    ]
