# Generated by Django 3.0.5 on 2021-07-07 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_auto_20210706_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientquanity',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_quantities', to='web.Ingredient', verbose_name='рецепт'),
        ),
        migrations.AlterField(
            model_name='ingredientquanity',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_quantities', to='web.Recipe', verbose_name='ингридент'),
        ),
    ]
