# Generated by Django 3.0.5 on 2021-07-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_auto_20210707_1748'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchases',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='purchases',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_user_recipe'),
        ),
    ]
