# Generated by Django 3.0.5 on 2021-07-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_auto_20210707_1757'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchases',
            name='unique_user_recipe',
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='ingredientquanity',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subscriber',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique__favorite__user_recipe'),
        ),
        migrations.AddConstraint(
            model_name='ingredientquanity',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique__ingredient_quanity__recipe_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='purchases',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique__purchases__user_recipe'),
        ),
        migrations.AddConstraint(
            model_name='subscriber',
            constraint=models.UniqueConstraint(fields=('author', 'subscriber'), name='unique__subscriber__author_subscriber'),
        ),
    ]
