# Generated by Django 3.0.5 on 2021-07-08 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_auto_20210707_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='breakfast_tag',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='dinner_tag',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='lunch_tag',
        ),
        migrations.CreateModel(
            name='RecipeTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин')], default='breakfast', max_length=9)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_tags', to='web.Recipe', verbose_name='теги рецепта')),
            ],
        ),
    ]
