# Generated by Django 3.0.5 on 2021-07-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_auto_20210708_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('color', models.SlugField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='RecipeTags',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, db_index=True, to='web.RecipeTag', verbose_name='Теги'),
        ),
    ]
