# Generated by Django 3.0.5 on 2021-07-11 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_auto_20210708_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientquanity',
            name='value',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Количество не может быть меньше 1')], verbose_name='Количество единиц в рецепте'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Время приготовления не меньше 1 минуты')], verbose_name='Время приготовления'),
        ),
    ]
