# Generated by Django 3.0.5 on 2021-07-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_auto_20210711_2300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='units',
            field=models.CharField(help_text='Единица измерения ингредиента. Обязательно к заполнению.', max_length=200, verbose_name='Единица измерения'),
        ),
    ]
